language: node_js

node_js:
  - stable

install:
  - npm install

before_install:
  - npm install peerDependency

script:
  - npm run test

# Send coverage data to Coveralls
after_success: npm run coverage